#!/usr/bin/env bash
args=("$@")

# parse command line arguments
while [ "$#" -gt 0 ]; do
  case "$1" in
    -h|--help)
      echo "Script to install the requirements for themo."
      echo "option --help: Print this help."
      echo "option --no-boost-install: Do not install boost library."
      echo "         Environment variable BOOST_ROOT needs to be set,"
      echo "         if boost libraries are installed in custom directory."
      echo "option --no-openfst-install: Do not install openfst library."
      echo "         Environment variable OPENFST_DIR needs to be set,"
      echo "         if openfst libraries are installed in custom directory."
      exit 0;;
    -b|--no-boost-install) no_boost_install=true; shift 1;;
    -o|--no-openfst-install) no_openfst_install=true; shift 1;;
    *) echo "unknown parameter $1!" >&2; exit 1;;
  esac
done

# install tools
cd tools
./install.sh "${args[@]}"
cd ..

# install themo
make themo
